### ISSUE TITLE
Possible to use for sharing within a lan ?

### ISSUE THREAD

**Issue by stuaxo** [troydm/udpt#3]
Hi,
   My scenario is that I have a bunch of clients on a lan.    They all have instances of transmission downloading torrents that have the same webseed.

I want to run a tracker running on each torrent, I'll then use transmissionrpc to point  at the other peers .... does this sound like it should work (for sharing download data between the peers) ?

Any things to watch out for ?

S

**Comment by troydm** [comment]
I'm not quite sure what you are trying to do actually. You can run only one instance of my udpt tracker and all the peers will not only download from some webseed running remotely but will also download blocks of data from each other too since this particular fork of udpt supports peers to be on the same lan and outside of it. Also one thing to watch out for your local lan users: each lan transmission client must have unique port configured in settings and your router with outside IP address should port forward that port to that particular lan user's IP address and port as described in the use case

**Comment by stuaxo** [comment]
I'm guessing I won't need port forwarding, since the outside connection is only ever via webseed.

(There are only ever peers inside the lan).

These all run off the same image, but I can make it so only one tracker runs at a time.

Cheers for the info :)
